name: Code Coverage (PHP)

on: [push, pull_request]

jobs:
  tests:
    name: Coverage
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: scout_testing
      DB_USER: root
      DB_PASSWORD: root
      DB_PORT: 3306
      DB_DRIVER: mysql

    steps:
      - uses: actions/checkout@v3

      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - name: Setup cache environment
        id: cache-env
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: 8.0
          extensions: mbstring,dom,fileinfo,mysql,imagick,bcmath,pcntl,zip,soap,intl,gd,exif,iconv
          key: extensions

      - name: Cache extensions
        uses: actions/cache@v1
        with:
          path: ${{ steps.cache-env.outputs.dir }}
          key: ${{ steps.cache-env.outputs.key }}
          restore-keys: ${{ steps.cache-env.outputs.key }}

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: mbstring,dom,fileinfo,mysql,imagick,bcmath,pcntl,zip,soap,intl,gd,exif,iconv
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "name=dir::$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-interaction --no-suggest

      - name: Run tests
        run: |
          mkdir -p build/logs
          ./vendor/bin/codecept run unit --coverage-xml coverage.xml;
          bash <(curl -s https://codecov.io/bash)
        env:
          APP_ENV: testing
